МоитеГуми/Models/Обява/ObqwaCategoryViewModel.cs
namespace МоитеГуми.Models.Обява
{
    public class ObqwaCategoryServiceModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

МоитеГуми/Models/Обява/ObqwaModel.cs
namespace МоитеГуми.Models.Обява
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using МоитеГуми.Services.Obqwi;
    using static МоитеГуми.Data.Models.DataConstatnt.Obqwa;
    public class ObqwaModel : IObqwaModel
    {
        [Required]
        [StringLength(carMax, MinimumLength = SizeMinLength, ErrorMessage = "Maximum: {0} symbols")]
        public string Marka { get; set; }

        [Required]
        [StringLength(int.MaxValue, MinimumLength = SizeMinLength, ErrorMessage = "{0} трябжа да е с дълйина между: {2} {1} symbols")]
        public string Description { get; set; }

        [Required]
        [StringLength(int.MaxValue, MinimumLength = SizeMinLength, ErrorMessage = "Maximum: {0} symbols")]
        public string Size { get; set; }


        [Display(Name = "Image Url")]
        [Url]
        public string ImageUrl { get; set; }


        [Range(TireYearMinValue, TireYearMaxvalue)]
        public int Year { get; set; }

        [Display(Name = "Category")]
        public int CategoryId { get; set; }//uzera go pra6ta

        public IEnumerable<ObqwaCategoryServiceModel> Categories { get; set; }
    }
}

МоитеГуми/Models/Обява/ObqwiSearchingModel.cs
namespace МоитеГуми.Models.Обява
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using МоитеГуми.Services.Obqwi;

    public class ObqwiSearchingModel
    {
        public const int ObqwiPerPage = 3;
        public string Marka { get; set; }// za dropdown na markite
        //towa e selektiranata Marka
        //tuka sa vsi4ki marki

        [Display(Name = "Търсене по размер")]
        public string Size { get; set; }

        [Display(Name = "Търсене по марка")]
        public string SearchTerm { get; set; }

        public ObqwiSorting Sorting { get; set; }

        public int CurrentPage { get; set; } = 1;

        public int CountObqwi { get; set; }

        public IEnumerable<string> Marki { get; set; }

        public IEnumerable<ObqwaServicesModel> Obqwi { get; set; }
    }
}

МоитеГуми/Areas/Admin/Controllers/ОбяваController.cs
namespace МоитеГуми.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using МоитеГуми.Services.Obqwi;

    public class ОбяваController : AdminController
    {
        private readonly IObqwiServices obqwa;

        public ОбяваController(IObqwiServices obqwa)
        {
            this.obqwa = obqwa;
        }

        public IActionResult All()
        {
            var obqvi = this.obqwa.All(publicOnly: false).Obqwa;

            return View(obqvi);
        }

        public IActionResult ChangeVisibility(int Id)
        {
            this.obqwa.ChangeVisibility(Id);

            return RedirectToAction(nameof(All));
        }
    }
}

МоитеГуми/Controllers/ОбяваController.cs
namespace МоитеГуми.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using МоитеГуми.Models.Обява;
    using Microsoft.AspNetCore.Authorization;
    using МоитеГуми.Infrastructure.Extensions;
    using МоитеГуми.Services.Obqwi;
    using МоитеГуми.Services.Dealers;
    using AutoMapper;

    using static WebConstatnts;

    public class ОбяваController : Controller
    {
        private readonly IDealerService dealers;
        private readonly IObqwiServices obqwi;
        private readonly IMapper mapper;

        public ОбяваController(
            IObqwiServices obqwi,
            IDealerService dealers,
            IMapper mapper
            )
        {
            this.obqwi = obqwi;
            this.dealers = dealers;
            this.mapper = mapper;
        }

        public IActionResult All([FromQuery] ObqwiSearchingModel query)
        {
            var queryResult = this.obqwi.All(
                query.Marka,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                ObqwiSearchingModel.ObqwiPerPage);


            var obqwiMarki = this.obqwi.AllMarki();

            query.CountObqwi = queryResult.CountObqwi;
            query.Marki = obqwiMarki;
            query.Obqwi = queryResult.Obqwa;

            return this.View(query);
        }

        [Authorize]
        public IActionResult Mine()
        {
            var myObqwi = this.obqwi.ByUser(this.User.Id());

            return View(myObqwi);
        }

        public IActionResult Details(int Id, string information)
        {
            var obqwa = this.obqwi.Details(Id);
            if (information != obqwa.GetInformation())
            {
                return BadRequest();
            }


            return View(obqwa);
        }

        [Authorize]
        public IActionResult Delete(int Id)
        {
            this.obqwi.DeleteAnoncment(Id);

            return RedirectToAction(nameof(All));
        }

        [Authorize]
        public IActionResult Create()
        {
            if (!this.dealers.IsDealer(this.User.Id()))
            {
                return RedirectToAction(nameof(DealersController.Create), "Dealers");
            }
            //ot infrastrukture
            return View(new ObqwaModel
            {
                Categories = this.obqwi.AllCategories()//vieto shte ima info za kategoriite
            });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(ObqwaModel obqva)
        {
            var dealerId = this.dealers.IdByUser(this.User.Id());

            if (dealerId == 0)
            {
                return RedirectToAction(nameof(DealersController.Create), "Dealers");
            }

            if (!this.obqwi.CategoryExist(obqva.CategoryId))
            {
                this.ModelState.AddModelError(nameof(obqva.CategoryId), "Category is dont exist");
            }

            if (!ModelState.IsValid)
            {
                //IF NOT VALID PAK ПОКАЗЖА ЖИУТО ДА СЕ ПОПАЛНИ
                obqva.Categories = this.obqwi.AllCategories();

                return View(obqva);
            }

           var obqwaId = this.obqwi.Create(
                obqva.Marka,
                obqva.Description,
                obqva.Year,
                obqva.CategoryId,
                obqva.ImageUrl,
                obqva.Size,
                dealerId);

            TempData[GlobalMessageKey] = "Вашата обява е запазена и чака за одобрение";

            return RedirectToAction(nameof(Details), new { id = obqwaId, information = obqva.GetInformation()});// Always REDIREKT
        }

        [Authorize]
        public IActionResult Edit(int Id)
        {
            var userId = this.User.Id();

            if (!this.dealers.IsDealer(userId) && !User.IsAdmin())
            {
                return RedirectToAction(nameof(DealersController.Create), "Dealers");
            }

            var currentObqwa = this.obqwi.Details(Id);

            if (currentObqwa.UserId != userId && !User.IsAdmin())
            {
                return Unauthorized();
            }

            var obqwaForm = this.mapper.Map<ObqwaModel>(currentObqwa);

            obqwaForm.Categories = this.obqwi.AllCategories();


            return View(obqwaForm);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(int Id, ObqwaModel obqva)
        {
            var dealerId = this.dealers.IdByUser(this.User.Id());

            if (dealerId == 0 && !User.IsAdmin())
            {
                return RedirectToAction(nameof(DealersController.Create), "Dealers");
            }

            if (!this.obqwi.CategoryExist(obqva.CategoryId) && !User.IsAdmin())
            {
                this.ModelState.AddModelError(nameof(obqva.CategoryId), "Category is dont exist");
            }

            if (!ModelState.IsValid)
            {
                //IF NOT VALID PAK ПОКАЗЖА ЖИУТО ДА СЕ ПОПАЛНИ
                obqva.Categories = this.obqwi.AllCategories();

                return View(obqva);
            }
            if (!this.obqwi.IsByDealer(Id, dealerId) && !User.IsAdmin())
            {
                return BadRequest();
            }

            this.obqwi.Edit(
                    Id,
                    obqva.Marka,
                    obqva.Description,
                    obqva.Year,
                    obqva.CategoryId,
                    obqva.ImageUrl,
                    obqva.Size,
                    this.User.IsAdmin());

            TempData[GlobalMessageKey] = $"Вашата обява редактирана {(this.User.IsAdmin() ? string.Empty : "чака одобрение")}";

            return RedirectToAction(nameof(Details), new { Id , information = obqva.GetInformation() });
        }

        [Authorize]
        //[HttpPost]
        public IActionResult Info(int Id)
        {
            var currentObqwa = this.obqwi.Info(Id);

            return View(currentObqwa);
        }



    }

}

МоитеГуми/Views/Обява/All.cshtml
@model ObqwiSearchingModel

@{
    ViewData["Title"] = "Всички Обяви";
}

<form method="get">
    <div class="row mb-5">
        @*otstoqnie ot drugitetablici mb-5*@
        @*ne sazdavam novi elementi  GEt*@
        @*polu4avame tyrsenoto kato string v kontrolera*@

        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Marka"></label>
                <select asp-for="Marka" class="form-control">
                    <option value="">All</option>
                    @foreach (var brand in Model.Marki)
                    {
                        <option value="@brand">@brand</option>
                    }
                </select>
            </div>
        </div>


        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="SearchTerm"></label>
                <input asp-for="SearchTerm" class="form-control" placeholder="Fulda,Michelin..">
            </div>
        </div>



        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Sorting"></label>
                <select asp-for="Sorting" class="form-control">
                    <option value="0" selected>Date Created</option>
                    <option value="1">Year</option>
                    <option value="2">Marka</option>
                </select>
            </div>
        </div>

    </div>
</form>


@if (!Model.Obqwi.Any())
{
    <h2 class="text-center">Няма Обяви</h2>
}

@{
    var previosPage = Model.CurrentPage - 1;
    if (previosPage < 1)
    {
        previosPage = 1;
    }

    var MaxPage = Math.Ceiling((double)Model.CountObqwi / ObqwiSearchingModel.ObqwiPerPage);
}

<div class="row mb-5">
    <div class="col-md-6">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Обява"
           asp-action="All"
           asp-route-currentPage="@previosPage"
           asp-route-brand="@Model.Marka"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)"><<</a>
    </div>
    <div class="col-md-6">
        <a class="btn btn-primary float-right @(Model.CurrentPage == MaxPage ? "disabled" : string.Empty)"
           asp-controller="Обява" asp-action="All"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-brand="@Model.Marka"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)">>></a>
    </div>
</div>

<partial name="_ObqwaPartial" model="@Model.Obqwi" />

МоитеГуми/Views/Обява/Create.cshtml
@model ObqwaModel

@{ ViewData["Title"] = "Добави"; }

<h3 class="heading-margin text-center">Добавяне на обява</h3>

<partial name="_ObqwaFormPartial" model="@Model" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

МоитеГуми/Views/Обява/Details.cshtml
@model ObqwaDetailsServiceModel

<div class="col-md-6 offset-3">
    <label asp-for="Marka">Модел</label>
    <h5>@Model.Marka @Model.Size</h5>
    <label asp-for="Description">Описание</label>
    <h5>@Model.Description</h5>
</div>

МоитеГуми/Views/Обява/Edit.cshtml
@model ObqwaModel

@{ ViewData["Title"] = "Редактиране"; }

<h3 class="heading-margin text-center">Редактиране на обява</h3>

<partial name="_ObqwaFormPartial" model="@Model" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

МоитеГуми/Views/Обява/Info.cshtml
@model Обява

@{ ViewData["Title"] = "Информация"; }

<h3 class="heading-margin text-center">Информация  </h3>



@*<div class="col-md-3">
    <div class="icon-box", align="center">
        <a asp-area="" asp-controller="ОбяваController" asp-action="Info" asp-route="Id">
            <img src="/МойтеГуми/Data/ImageUrl" alt=""/>
        </a>
    </div>
</div>*@

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        @*6 i izmesti 3 pri malak 12 pri golqm 8 no izmesti 2 i pri xl  *@

        @* ofseta samo na sredni ekrani  *@
        @*<div offset - 3 class="col-5">izmesti 3 i zapo4ni 5reda ob6to 12 col- 12 na malki ekrani 12*@
        @*enctype="multipart/form-data"*@ <!--da poddarja failove-->
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="Marka">Модел</label>
                <input asp-for="Marka" class="form-control">
            </div>
            <div class="form-group">
                <label asp-for="Description">Описание</label>
                <input asp-for="Description" class="form-control">

            </div>
            <div class="form-group">
                <label asp-for="Size">Размер</label>
                <input asp-for="Size" class="form-control">
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl">Снимка</label>
                <input asp-for="ImageUrl" class="form-control">
            </div>
            <div class="form-group">
                <label asp-for="Year">Година на производство</label>
                <input asp-for="Year" class="form-control">
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

МоитеГуми/Views/Обява/Mine.cshtml
@model IEnumerable<ObqwaServicesModel>

@{
    ViewData["Title"] = "Моите Обяви";
    ViewBag.Edit = true;
 }


@if (!Model.Any())
 {
    <h2 class="text-center">Няма Обяви</h2>
 }



<partial name="_Obqwapartial" model="@Model" />

МоитеГуми/Views/Обява/_ObqwaFormPartial.cshtml
@model ObqwaModel


<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        @*6 i izmesti 3 pri malak 12 pri golqm 8 no izmesti 2 i pri xl  *@

        @* ofseta samo na sredni ekrani  *@
        @*<div offset - 3 class="col-5">izmesti 3 i zapo4ni 5reda ob6to 12 col- 12 na malki ekrani 12*@
        @*enctype="multipart/form-data"*@ <!--da poddarja failove-->
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="Marka">Модел</label>
                <input asp-for="Marka" class="form-control" placeholder="Fulda,Michelin..">
                <span class="small text-danger" asp-validation-for="Marka"></span> @*ako ima nevalidni 6te gi pi6e tuka*@
            </div>
            <div class="form-group">
                <label asp-for="Description">Описание</label>
                <input asp-for="Description" class="form-control" placeholder="Описание на гумите...">
                <span asp-validation-for="Description" class="small text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Size">Размер</label>
                <input asp-for="Size" class="form-control" placeholder="Размер на гумите 205/55/16...">
                <span asp-validation-for="Size" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl">Снимка</label>
                <input asp-for="ImageUrl" class="form-control" placeholder="Снимка на гумите">
                <span asp-validation-for="ImageUrl" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year">Година на производство</label>
                <input asp-for="Year" class="form-control" placeholder="Година на производство">
                <span asp-validation-for="Year" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId">Категория</label>
                <select asp-for="CategoryId" class="form-control">
                    @foreach(var category in Model.Categories)
                     {
                         <option value="@category.Id">@category.Name</option>
                     }
                </select>
            </div>


            <input class="btn btn-primary float-right mt-4" type="submit" value="Запази" />

        </form>
    </div>
</div>

МоитеГуми/Views/Обява/_ObqwaPartial.cshtml
@model IEnumerable<ObqwaServicesModel>

<div class="row">
    @foreach (var obqva in Model)
    {
     <div class="col-md-4">
         <div class="card mb-3">
             <img src="@obqva.ImageUrl" class="card-img-top" alt="@obqva.Marka - @obqva.Year (@obqva.CategoryName)">
             <div class="card-body text-center">
                 <h5 class="card-title text-center">@obqva.Marka @obqva.Size @obqva.CategoryName @obqva.Year</h5>
                 <a asp-controller="Обява" asp-action="Info" asp-route-id="@obqva.Id" asp-route-information="@obqva.GetInformation()" class="btn btn-primary">Информация</a>
                 @if (ViewBag.Edit == true || User.IsAdmin())
                 {
                     <a asp-controller="Обява" asp-action="Edit" asp-route-id="@obqva.Id" class="btn btn-warning">Редактирай</a>
                     <a asp-controller="Обява" asp-action="Delete" asp-route-id="@obqva.Id" class="btn btn-danger">Триене</a>
                 }
             </div>
         </div>
     </div>
    }
</div>